// What a new coach account starts with. Each coach gets their own copy
// (see seedCoachLibrary in tenancy.ts) and can rename, refile, add or delete
// anything in it: coaches name movements their own way, and one coach's
// changes never reach another's library.

/** Exercises by picker group (the slugs in MUSCLE_GROUPS). */
export const EXERCISE_PRESETS: Record<string, string[]> = {
  back: [
    "Lat Pulldown",
    "Seated Cable Row",
    "Barbell Row",
    "Dumbbell Row",
    "Chest-Supported Row",
    "Pull-Up",
    "Chin-Up",
    "Assisted Pull-Up",
    "Straight-Arm Pulldown",
    "T-Bar Row",
    "Deadlift",
    "Romanian Deadlift",
    "Face Pull",
    "Back Extension",
    "Rear Delt Fly",
  ],
  chest: [
    "Barbell Bench Press",
    "Incline Barbell Bench Press",
    "Dumbbell Bench Press",
    "Incline Dumbbell Press",
    "Flat Chest Press Machine",
    "Incline Chest Press Machine",
    "Push-Up",
    "Cable Fly",
    "Pec Deck",
    "Dumbbell Fly",
    "Dips",
    "Decline Bench Press",
  ],
  legs: [
    "Back Squat",
    "Front Squat",
    "Goblet Squat",
    "Leg Press",
    "Hack Squat",
    "Bulgarian Split Squat",
    "Walking Lunge",
    "Leg Extension",
    "Seated Leg Curl",
    "Lying Leg Curl",
    "Hip Thrust",
    "Glute Bridge",
    "Step-Up",
    "Calf Press",
    "Standing Calf Raise",
    "Seated Calf Raise",
    "Hip Adduction Machine",
    "Hip Abduction Machine",
  ],
  arms: [
    "Barbell Curl",
    "Incline Dumbbell Curl",
    "Seated Alternating Dumbbell Curl",
    "Hammer Curl",
    "Preacher Curl",
    "Cable Curl",
    "Bar Tricep Pushdown",
    "Rope Tricep Pushdown",
    "Overhead Tricep Extension",
    "Skull Crusher",
    "Close-Grip Bench Press",
    "Overhead Press",
    "Seated Dumbbell Shoulder Press",
    "Side Raise Machine",
    "Dumbbell Lateral Raise",
    "Cable Lateral Raise",
    "Front Raise",
    "Wrist Curl",
  ],
  abs: [
    "Plank",
    "Side Plank",
    "Hanging Leg Raise",
    "Hanging Knee Raise",
    "Cable Crunch",
    "Ab Wheel Rollout",
    "Dead Bug",
    "Bicycle Crunch",
    "Russian Twist",
    "Mountain Climber",
    "Decline Sit-Up",
    "Pallof Press",
  ],
  cardio: [
    "Treadmill Walk (incline)",
    "Treadmill Run",
    "Stationary Bike",
    "Assault Bike",
    "Rowing Machine",
    "Stair Climber",
    "Elliptical",
    "Jump Rope",
    "Outdoor Run",
    "Outdoor Walk",
    "Swimming",
    "Sled Push",
  ],
};

/** Check-in metric template packs, from the coach's Week Tracker sheet. */
export const METRIC_TEMPLATE_PRESETS: { category: string; frequency: "daily" | "weekly"; unit: string; items: string[] }[] = [
  {
    category: "Stress",
    frequency: "weekly",
    unit: "/10",
    items: ["Stress factors of the last week", "Work", "Private", "Social", "Stress factors getting in the way of your goals", "Managing stress"],
  },
  {
    category: "Nutrition",
    frequency: "weekly",
    unit: "/10",
    items: ["Consistency of meal timing", "Quality of nutrition", "Bloatedness", "Stool", "Enjoyment of eating", "Cravings", "Hunger"],
  },
  {
    category: "Training",
    frequency: "weekly",
    unit: "/10",
    items: ["Enjoyment of training", "Recovery", "Adherence to programme", "Fatigue during training"],
  },
  {
    category: "General Wellbeing",
    frequency: "weekly",
    unit: "/10",
    items: ["Happiness", "Development", "Contribution to goals", "Motivation", "Habit development", "Satisfaction with the week"],
  },
  { category: "Optional", frequency: "weekly", unit: "/10", items: ["Menstruation"] },
];
